server:
  port: 8050
eureka:
  client:
    service-url:
      defaultZone: http://laudy:laudy123@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
spring:
  application:
    name: file-upload-service
  http:
    multipart:
      max-file-size: 2000Mb     # Max file size, д╛хо1M
      max-request-size: 2500Mb  # Max request size, д╛хо10M

