server:
  port: 8020
spring:
  application:
    name: movie-consumer-feign-service
eureka:
  client:
    service-url:
      defaultZone: http://laudy:laudy123@localhost:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
feign:
#  compression:
#    request:
#      enabled: true
#      mime-types: text/xml,application/xml,application/json
#      min-request-size: 2048
#    response:
#      enabled: true
  hystrix:
    enabled: true