server:
  port: 8031

spring:
  application:
    name: hystrix-turbine
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://laudy:laudy123@localhost:8761/eureka/
  instance:
    prefer-ip-address: true

#turbine:
#  app-config: movie-consumer-service, movie-consumer-feign-service
#  cluster-name-expression: "'default'"