server:
  port: 8010
spring:
  application:
    name: movie-consumer-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true