server:
  port: 8010

spring:
  application:
    name: movie-consumer-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://laudy:laudy123@localhost:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true

ribbon:
  eager-load:
    enabled: true
#    clients: simple-user-service

